[supervisord]
logfile=/home/frappe/frappe-bench/logs/supervisord.log
pidfile=/home/frappe/frappe-bench/logs/supervisord.pid
childlogdir=/home/frappe/frappe-bench/logs

[unix_http_server]
file=/tmp/supervisor.sock

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:web]
command=bench start
directory=/home/frappe/frappe-bench
autostart=true
autorestart=true
stderr_logfile=/home/frappe/frappe-bench/logs/web.err.log
stdout_logfile=/home/frappe/frappe-bench/logs/web.out.log
user=frappe
